"""Report generator: creates structured Markdown and JSON bug bounty reports."""
import json
from datetime import datetime
from typing import List
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.models import Target, Finding, Report
from app.notifications import notify_report_generated


SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}


def _severity_badge(severity: str) -> str:
    badges = {
        "critical": "🔴 CRITICAL",
        "high": "🟠 HIGH",
        "medium": "🟡 MEDIUM",
        "low": "🔵 LOW",
        "info": "⚪ INFO",
    }
    return badges.get(severity, severity.upper())


def _build_markdown_report(target: Target, findings: List[Finding]) -> str:
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    sorted_findings = sorted(findings, key=lambda f: SEVERITY_ORDER.get(f.severity, 99))

    severity_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
    for f in findings:
        severity_counts[f.severity] = severity_counts.get(f.severity, 0) + 1

    lines = [
        f"# Bug Bounty Report — {target.name}",
        f"",
        f"**Target URL:** {target.url}  ",
        f"**Platform:** {target.platform}  ",
        f"**Generated:** {now}  ",
        f"**Total Findings:** {len(findings)}  ",
        f"",
        "## Severity Summary",
        "",
        "| Severity | Count |",
        "|----------|-------|",
        f"| 🔴 Critical | {severity_counts['critical']} |",
        f"| 🟠 High | {severity_counts['high']} |",
        f"| 🟡 Medium | {severity_counts['medium']} |",
        f"| 🔵 Low | {severity_counts['low']} |",
        f"| ⚪ Info | {severity_counts['info']} |",
        "",
    ]

    if target.scope_details:
        lines += ["## Scope", "", target.scope_details, ""]

    lines += ["## Findings", ""]

    for i, finding in enumerate(sorted_findings, 1):
        lines += [
            f"---",
            f"",
            f"### Finding #{i}: {finding.title}",
            f"",
            f"**Severity:** {_severity_badge(finding.severity)}  ",
            f"**Category:** {finding.category.upper()}  ",
            f"**CVSS Score:** {finding.cvss_score or 'N/A'}  ",
            f"**Confidence:** {finding.confidence.title()}  ",
            f"**Affected URL:** `{finding.affected_url or target.url}`  ",
            f"**First Detected:** {finding.first_seen.strftime('%Y-%m-%d')}  ",
            f"",
            f"#### Description",
            f"",
            finding.description or "",
            f"",
            f"#### Evidence",
            f"",
            f"```",
            finding.evidence or "See description above.",
            f"```",
            f"",
        ]

        if finding.reproduction_steps:
            lines += [
                f"#### Steps to Reproduce",
                f"",
                finding.reproduction_steps,
                f"",
            ]

        if finding.remediation:
            lines += [
                f"#### Remediation",
                f"",
                finding.remediation,
                f"",
            ]

    lines += [
        "---",
        "",
        "## Disclaimer",
        "",
        "*This report was generated by the automated Bug Bounty Tracker tool for authorized security research purposes only.*",
        f"*Report generated at {now}*",
    ]

    return "\n".join(lines)


def _build_json_report(target: Target, findings: List[Finding]) -> str:
    sorted_findings = sorted(findings, key=lambda f: SEVERITY_ORDER.get(f.severity, 99))
    severity_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
    for f in findings:
        severity_counts[f.severity] = severity_counts.get(f.severity, 0) + 1

    report_data = {
        "report_metadata": {
            "target_name": target.name,
            "target_url": target.url,
            "platform": target.platform,
            "scope_details": target.scope_details,
            "generated_at": datetime.utcnow().isoformat(),
            "total_findings": len(findings),
            "severity_summary": severity_counts,
        },
        "findings": [
            {
                "id": f.id,
                "title": f.title,
                "severity": f.severity,
                "category": f.category,
                "cvss_score": f.cvss_score,
                "confidence": f.confidence,
                "affected_url": f.affected_url or target.url,
                "description": f.description,
                "evidence": f.evidence,
                "reproduction_steps": f.reproduction_steps,
                "remediation": f.remediation,
                "cve_id": f.cve_id,
                "first_seen": f.first_seen.isoformat(),
                "last_seen": f.last_seen.isoformat(),
                "status": f.status,
            }
            for f in sorted_findings
        ],
    }
    return json.dumps(report_data, indent=2)


async def generate_report(target_id: int, db: AsyncSession) -> Report:
    """Generate a full bug bounty report for a target."""
    # Fetch target
    target_result = await db.execute(select(Target).where(Target.id == target_id))
    target = target_result.scalar_one_or_none()
    if not target:
        raise ValueError(f"Target #{target_id} not found")

    # Fetch non-false-positive findings
    findings_result = await db.execute(
        select(Finding).where(
            Finding.target_id == target_id,
            Finding.status != "false_positive",
        )
    )
    findings = findings_result.scalars().all()

    severity_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
    for f in findings:
        severity_counts[f.severity] = severity_counts.get(f.severity, 0) + 1

    markdown_content = _build_markdown_report(target, findings)
    json_content = _build_json_report(target, findings)

    report = Report(
        target_id=target_id,
        title=f"Bug Bounty Report — {target.name} ({datetime.utcnow().strftime('%Y-%m-%d')})",
        content_markdown=markdown_content,
        content_json=json_content,
        findings_count=len(findings),
        severity_breakdown=json.dumps(severity_counts),
        generated_at=datetime.utcnow(),
    )
    db.add(report)
    await db.commit()
    await db.refresh(report)

    await notify_report_generated(db, report.id, target.name, len(findings))
    return report
